server:
  error:
    include-stacktrace: never

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/daycare-system-db?createDatabaseIfNotExist=true
    username: root
    password :

  security:
    user:
      name: "Test User"
      password: "123456"